spring:
  application:
    name: qvuw20800-job

  #  datasource:
  #    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
  #    username: your_db_user
  #    password: your_db_password
  #    driver-class-name: oracle.jdbc.OracleDriver
  #    hikari:
  #      maximum-pool-size: 10
  #      minimum-idle: 2
  #      idle-timeout: 30000
  #      pool-name: HikariCP
  #      max-lifetime: 60000

  batch:
    job:
      enabled: false  # 실행 시 어떤 Job을 실행할지 명시해야 하므로 false
    jdbc:
      initialize-schema: never  # 메타테이블 수동 생성 시
    datasource:
      orasfqt-ssfqgvut:
        url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
        username: your_user
        password: your_password
        driver-class-name: oracle.jdbc.OracleDriver


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.bzbatch.sample.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.bzbatch.sample: DEBUG
    org.mybatis: DEBUG
    org.springframework.jdbc.core: TRACE

